### ISSUE TITLE
VTE Configuration Issue alert still showing

### ISSUE THREAD

**Issue by escobera** [gnunn1/terminix#467]
Hello there.

I'm using terminix on linux mint 18 MATE. Latest version from webupd8 ppa.

I did the following steps.

* Added `source /etc/profile.d/vte.sh` to teh end of my .zshrc
* Symlinked vte.sh -> /etc/profile.d/vte-2.91.sh

But I'm still getting the warning. Is there a way to debug this?

**Comment by gnunn1** [comment]
This might be a bug in terminix as I vagualy remember fixing some issues with this dialog after the last stable release. Can you check if the prompt_command is sourced in terminix after you made those changes, just run the following from the terminix:

```
echo $PROMPT_COMMAND
```

You should see ```__vte_osc7``` included in it.

**Comment by escobera** [comment]
It prints nothing.

even after manually calling `source /etc/profile.d/vte.sh` it remains empty.

**Comment by phw** [comment]
It might be related, but occasionally when splitting terminals the VTE warning shows up for me, too, but usually it does not. I have not yet found out why and how to reproduce this reliable. And it is very seldom.

**Comment by gnunn1** [comment]
@escobera I use bash myself, I'll have a look tonite with zsh just to re-confirm it works for me with master and that PROMPT_COMMAND is set as expected.

You could also try enabling the login shell option under the Command tab in the profile settings and see if that helps.

**Comment by gnunn1** [comment]
@phw thanks, I'll keep that in mind when I'm looking at it. That warning dialog is a bit of a nuisance to get working perfectly with all of the permutations and combinations.

**Comment by escobera** [comment]
http://superuser.com/questions/735660/whats-the-zsh-equivalent-of-bashs-prompt-command

Looks like PROMPT_COMMAND is bash-only.

**Comment by gnunn1** [comment]
I tested this in the current version in github and it works as expected, as I said I'm pretty sure I fixed this since the last stable. 

You can test if the warning is just spurious pretty easily, just start terminix and in the shell change to some directory. Next split the terminal and check the directory in the new terminal. If it's the same as the directory you switched too then the warning is spurious and can be ignored by selecting the cjeckbox on the dialog.

**Comment by gnunn1** [comment]
I'm closing this, as stated this is fixed in master and will be in the forthcoming 1.3.0 release in the next couple of weeks.

**Comment by blonchkman** [comment]
Hello,
FYI: using terminix 1.2.0-1 webupd8 package on xenial, the  vte warning shows only when launching terminix with session option `-s´. It doesn't show by launching terminix without `-s´ option. 
Kind regards

**Comment by gnunn1** [comment]
@blonchkman I think this has been fixed in 1.3.0 which I released on Friday. Please test that and if it is still a problem open a new issue for it.

**Comment by blonchkman** [comment]
@gnunn1

Yes, the behavior mentioned disappeared with the new version.

It's a fantastic work!!
Thank you very much for this essential tool.

Kind regards


2016-10-02 14:24 GMT+02:00 Gerald Nunn <notifications@github.com>:

**Comment by gapplef** [comment]
I am using the webupd8 ppa on Ubuntu Gnome 16.10
Terminix version is 1.4.9-2.0.0
I still have the problem after enable the`Run command as a login shell` in Profile>Command
*No* problem when source /etc/profile.d/vte-2.91.sh in .zshrc
