### ISSUE TITLE
With infinite history, scrolling become slow even after resetting terminal

### ISSUE THREAD

**Issue by bagage** [gnunn1/terminix#733]
If I enable infinite scrolling (no lines limitation) and use a terminix tab for a long time, the scroll becomes very rough even if the tab actually contains almost nothing (because I typed `reset` in it). 
If I open a new tab, then scrolling restarts to be smooth again.

It's unclear how to reproduce it, but I think by having looots of lines printed at a given time, then typing `reset`, having some output and trying to scroll should be enough.

Running debian with packaged version 1.4.2.3.

**Comment by f2404** [comment]
@bagage Can you check if CPU usage increases when scrolling, like described in https://github.com/gnunn1/terminix/issues/669#issuecomment-275996264?

**Comment by bagage** [comment]
@f2404 Indeed I missed this issue - most of the symptoms are similar. I'll build terminix from master and see if it was already solved.

**Comment by gnunn1** [comment]
@bagage Any update on this, is it fixed in master for you?

**Comment by bagage** [comment]
It's unclear since I have hard time reproducing it. For now let's close it, I'll reopen if I manage to reproduce it :).

**Comment by bagage** [comment]
I can reproduce the issue on master, shall I continue on this issue or go on #669?

I don't know exactly what helps to reproduce the issue, but it **seems** that having multiple subviews helps to reproduce it. Running `htop` and `top` in a subview seems to help another view to start lagging…

@gnunn1 What could I do to help on this? Obviously trying to find steps to reproduce would help, but apart of that? I'll try, as your suggestion states on #669, to comment out this:

`vte.addOnScroll(&onTerminalScroll);`

**Comment by gnunn1** [comment]
What do you mean by subview, multiple split terminals?

Here are a few suggestions for things to try:

a. Test to see if you can reproduce the issue in gnome-terminal, terminix uses the same VTE widget that gnome-terminal does for terminal emulation and it's possible the issue in that component rather then terminix itself.

b. Try commenting out vte.addOnScroll line you referenced to see if it makes any difference. Note that I already fixed one thing that was causing a slow-down in there but maybe there is something else.

c. If you are using a Terminix patched VTE try switching to the normal version without patches, this will disable triggers.

**Comment by gnunn1** [comment]
@bagage Did you get a chance to try any of those items?

**Comment by bagage** [comment]
@gnunn1 Yeah, I have currently commented out the callback (test `b`). And did not encounter the issue yet… I'll do the `a` test (use gnome-terminal) to see if I can reproduce.
For `c`, I have no idea if my VTE is patched or not.

**Comment by gnunn1** [comment]
Just type ```terminix --version``` and post the results here, I can tell if it's patched from that.

**Comment by bagage** [comment]
OK, here it is:

```
2017-02-09T20:56:42.190:app.d:main:36 CWD = /tmp
2017-02-09T20:56:42.190:app.d:main:40 PWD = /tmp
2017-02-09T20:56:42.190:app.d:main:51 UHD = /home/gautier
2017-02-09T20:56:42.244:app.d:main:79 Starting terminix with 2 arguments...
2017-02-09T20:56:42.244:app.d:main:81 arg[0] = terminix
2017-02-09T20:56:42.244:app.d:main:81 arg[1] = --version
Versions
	Terminix version: 1.4.3-0.0.1
	VTE version: 0.46
	GTK Version: 3.22.7

Terminix Special Features
2017-02-09T20:56:42.249:vte.d:checkVTEFeature:81 Background draw disabled
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by miekg** [comment]
Seeing the same thing, but in a precompiled version: 1.4.2-1~webupd8~xenial0

**Comment by gnunn1** [comment]
@miekg Please try building from master, I've fixed one significant thing causing this there.

**Comment by miekg** [comment]
Cool thank you.

Seeing the deps (DMD) I'll just wait for an .deb update.

**Comment by bagage** [comment]
So I do not reproduce it with gnome-terminal nor while commenting the callback @gnunn1. But I can reproduce it on terminix master.

**Comment by gnunn1** [comment]
gnome-terminal as far as I can tell doesn't connect to the scroll-event signal in VTE. The code I'm using in the event handler is pretty minimal and shouldn't be causing any performance issues unless you have the zoom on scroll wheel option enabled:

```
    bool onTerminalScroll(Event event, Widget widget) {
        if (vte !is null && _controlWheelZoom && (event.scroll.state & ModifierType.CONTROL_MASK) && !(event.scroll.state & ModifierType.SHIFT_MASK) && !(event.scroll.state & ModifierType.MOD1_MASK)) {
            ScrollDirection zoomDirection = event.scroll.direction;
            if (zoomDirection == ScrollDirection.SMOOTH) {
                zoomDirection = (event.scroll.deltaY <= 0)?ScrollDirection.UP: ScrollDirection.DOWN;
            }
            if (zoomDirection == ScrollDirection.UP) {
                zoomIn();
            } else if (zoomDirection == ScrollDirection.DOWN) {
                zoomOut();
            }
            return true;
        }
        return false;
    }
```

The only thing I can think of is binding to the scroll event itself is causing an issue, maybe a bug in VTE. I'll adjust the code so it only binds to the event if the zoom on scroll wheel option is enabled.

**Comment by gnunn1** [comment]
@bagage Please try out the latest commit and see if it fixes the issue for you. It should be semantically the same as commenting out the event handler since the event handler will only be binded if the "Zoom the terminal using <Control> with mouse wheel" option in behaviors. Thus my expectation is:

Zoom option off - no issue
Zoom option on - issue occurs

I don't think I can fix it for when the Zoom option is on since there is nothing in my code that is problematic. The only potential issue I can think of is that GtkD needs to generate an Event object for this, perhaps when scrolling up and down it's slowing things down. In my own testing the calls to this event handler do not seem excessive but it's the only other thing I can think of.

**Comment by gnunn1** [comment]
And after typing that I realize there is a struct version of the event handler which doesn't require creating an object each time's invoked so I've updated the code to use that. Anyway, @bagage please test this with the zoom option off and the zoom option on, I'm quite curious to see if it's now fixed for both cases.

**Comment by bagage** [comment]
First I tested your first fix (commit d383eb8) but I could NOT reproduce the issue, evenwith zoom option on. I mean any change was making terminix suffer (toggle fullscreen, zoom with `^+`, etc.), but zooming with the wheel was always smooth.
I'm testing the newest version now - sorry it always takes a bit of time to test it :).

**Comment by sirselim** [comment]
Sorry to resurrect this issue, and I understand it appears to be solved for most people (as per #669), but I've been unable to get to the bottom of it on my machine.

I had been using the version from the Debian sid repositories (1.6.4-1) and have now just built from the master branch:
```sh
~$ tilix --version
Versions
	Tilix version: 1.6.5-0.0.2
	VTE version: 0.48
	GTK Version: 3.22.19

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```
I'm still seeing laggy scrolling, both when using the mousewheel and the scroll bar at the side. I don't see this behaviour from gnome-terminal. I have tried turning on/off zoom option, various VTE patches, and as above building from source.

Any insight? I'm more than happy to help with testing and providing more information.

Thanks for the amazing program!

**Comment by gnunn1** [comment]
The most likely culprit would be triggers but you have those disabled. You can try commenting out the ```        vte.addOnContentsChanged(delegate(VTE)``` handler on line 936 to the end of the brace on line 986 as the next most likely culprit.

**Comment by sirselim** [comment]
Thanks for the quick response. I just ran a system update to ensure I'm running all packages as updated as possible, VTE: 0.50 and GTK: 3.22.21. 

I rebuilt tilix, commenting out the section from lines 936-986 and the problem still persists.

**Comment by sirselim** [comment]
OK, so turning off the scroll bars has stopped the lag and CPU load. Turning them back on it reappears.

**Comment by gnunn1** [comment]
In Preferences under Appearance, try turning off the overlay scrollbar. This will cause Tilix to use a separate scrollbar same as gnome-terminal. I suspect it will also fix the problem.

**Comment by sirselim** [comment]
You are correct, after turning off overlay and turning on scrollbars again (and a restart) there is no lag. I might run without scrollbars as it looks quite nice. :)

Thank you for your help and this great terminal emulator.
